### ISSUE TITLE
Option specifying search directories

### ISSUE THREAD

**Issue by gsingh93** [jturcotte/SublimeSwitchFileDeluxe#1]
Currently, it looks like the plugin will only search the directories of the currently opened files. However, it's often the case that I have some .cpp file open in /src and I have no files from /include open, but I want to open the header file for the .cpp file I'm currently editing. In this case, the plugin won't open the header file.

Could you add a config option that would let us specify which directories to always search in for files (i.e. src and include)? Or alternatively search everything in the project folders.

**Comment by jturcotte** [comment]
I thought about it and allowing paths in a configuration file would be quite a nightmare to maintain for users.

The best solution would be if Sublime Text would allow querying its file database and do the matching ourselves, but I don't see how it can be possible with the current API.

I added a simple fallback and pushed it to the beta branch, please try it out and let me know if you can think of something better. It should only show up when only a few files are already opened anyway.

I'll push it to master once I tested it for one or two days.
